#!/bin/bash

split_forks_bin='/usr/bin/SplitForks'

if [ ! -x "${split_forks_bin}" ]; then
	echo "ERROR! Expected 'SplitForks' binary to exist and be executable at '${split_forks_bin}, but it's not! Unable to proceed."
	exit 1
fi

find . ! -iname ".git" -type f -exec "${split_forks_bin}" {} \;
find . -name "._*" -exec git add -f {} +
